# SPDX-FileCopyrightText: 2024 FLECS Technologies GmbH <info@flecs.tech>
#
# SPDX-License-Identifier: MIT
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '17 3 * * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}