# SPDX-FileCopyrightText: 2024 FLECS Technologies GmbH <info@flecs.tech>
#
# SPDX-License-Identifier: MIT
name: Checks the rust source code of the project. This includes format, linting, unit tests, compiling, code coverage and documentation.
run-name: Check ${{ github.repository }} at ${{ github.ref_name }}
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    container: flecspublic.azurecr.io/flecs-build:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build project
        run: cargo build --all-targets --all-features --locked
      - name: Validate code format
        run: cargo fmt --check --all
      - name: Lint rust code
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: Run tests
        run: cargo test --all-features --locked
      - name: Create coverage report
        run: cargo llvm-cov --html --all-features --locked
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: target/llvm-cov/html/
      - name: Build documentation
        run: cargo doc --all-features --locked