# SPDX-FileCopyrightText: 2024 FLECS Technologies GmbH <info@flecs.tech>
#
# SPDX-License-Identifier: MIT
name: vulnerability_scan.yml
on:
  workflow_call:
    inputs:
      fix:
        type: boolean
        default: false
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo audit
        run: cargo install cargo-audit --features=fix
      - name: Fix vulnerabilities
        if: ${{ inputs.fix }}
        # TODO: Automatically fix dependencies (without --dry-run) and create PR
        run: cargo audit fix --dry-run
      - name: Scan dependencies for vulnerabilities
        if: ${{ !inputs.fix }}
        run: cargo audit
